backend:
  name: github # Use the GitHub backend
  repo: devzendcode2025/towingsite # Path to your GitHub repository
  branch: master # Branch to update

media_folder: 'public/images/uploads' # Where media files will be stored
public_folder: '/images/uploads' # The src attribute for the media file

collections:
  - name: 'pages'
    label: 'Page Content'
    files:
      - label: 'Hero Section'
        name: 'hero'
        file: 'content/hero.md'
        fields:
          - { label: 'Slides', name: 'slides', widget: 'list', fields: [
              { label: 'Title', name: 'title', widget: 'string' },
              { label: 'Subtitle', name: 'subtitle', widget: 'string' },
              { label: 'Button Text', name: 'button_text', widget: 'string' },
              { label: 'Button Link', name: 'button_link', widget: 'string' },
              { label: 'Image', name: 'image', widget: 'image' }
            ]}
      - label: 'About Section'
        name: 'about'
        file: 'content/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
          - { label: 'Phone Number', name: 'phone_number', widget: 'string' }
          - { label: 'Features', name: 'features', widget: 'list', field: { label: 'Feature', name: 'feature', widget: 'string' } }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Services Section'
        name: 'services'
        file: 'content/services.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
          - { label: 'Services', name: 'services', widget: 'list', fields: [
              { label: 'Title', name: 'title', widget: 'string' },
              { label: 'Description', name: 'description', widget: 'string' }
            ]}
      - label: 'Gallery Section'
        name: 'gallery'
        file: 'content/gallery.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
          - { label: 'Gallery Images', name: 'gallery_images', widget: 'list', field: { label: 'Image', name: 'image', widget: 'image' } }
      - label: 'Why Choose Us Section'
        name: 'why-choose-us'
        file: 'content/why-choose-us.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Points', name: 'points', widget: 'list', field: { label: 'Point', name: 'point', widget: 'string' } }
      - label: 'Contact Section'
        name: 'contact'
        file: 'content/contact.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
          - { label: 'Phone Number', name: 'phone_number', widget: 'string' }
          - { label: 'Availability', name: 'availability', widget: 'string' }
          - { label: 'Email Address', name: 'email_address', widget: 'string' }
          - { label: 'Location', name: 'location', widget: 'string' }
      - label: 'Footer'
        name: 'footer'
        file: 'content/footer.md'
        fields:
          - { label: 'Company Name', name: 'company_name', widget: 'string' }
          - { label: 'Slogan', name: 'slogan', widget: 'string' }
          - { label: 'Copyright Year', name: 'copyright_year', widget: 'string' }
          - { label: 'Address', name: 'address', widget: 'string' }
          - { label: 'Phone Number', name: 'phone_number', widget: 'string' }
          - { label: 'Email Address', name: 'email_address', widget: 'string' }
          - { label: 'Links', name: 'links', widget: 'list', fields: [
              { label: 'Text', name: 'text', widget: 'string' },
              { label: 'Href', name: 'href', widget: 'string' }
            ]}
          - { label: 'Services Links', name: 'services_links', widget: 'list', fields: [
              { label: 'Text', name: 'text', widget: 'string' },
              { label: 'Href', name: 'href', widget: 'string' }
            ]}
          - { label: 'Social Links', name: 'social_links', widget: 'list', fields: [
              { label: 'Icon', name: 'icon', widget: 'string' },
              { label: 'Href', name: 'href', widget: 'string' }
            ]}